In [1]:
#Exp no.: 4

In [2]:
#Aim: Data preprocessing_data cleaning_missing value treatment

In [3]:
#Name: raj d. avzade
#Roll no.: 04
#sec.: 3-c
#subject: DSS
#date: 20/08/2026

In [6]:
import pandas as pd

In [7]:
import os

In [8]:
os.getcwd()

'C:\\Users\\LENOVO'

In [11]:
os.chdir(r"C:\users\LENOVO\Desktop")

In [12]:
data=pd.read_csv("train_and_test2.csv")

In [13]:
data.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [14]:
data.tail()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
1304,1305,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1306,1307,38.5,7.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1307,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1308,1309,28.0,22.3583,0,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

In [15]:
data.describe()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
count,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.0,1309.0,1309.0,1309.0,1309.0,...,1309.0,1309.0,1309.0,1309.000000,1309.0,1309.0,1307.000000,1309.0,1309.0,1309.000000
mean,655.000000,29.503186,33.281086,0.355997,0.498854,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.294882,0.0,0.0,1.492731,0.0,0.0,0.261268
std,378.020061,12.905241,51.741500,0.478997,1.041658,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.837836,0.0,0.0,0.814626,0.0,0.0,0.439494
min,1.000000,0.170000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.000000,0.0,0.0,0.000000,0.0,0.0,0.000000
25%,328.000000,22.000000,7.895800,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.000000,0.0,0.0,1.000000,0.0,0.0,0.000000
50%,655.000000,28.000000,14.454200,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,0.000000
75%,982.000000,35.000000,31.275000,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,1.000000
max,1309.000000,80.000000,512.329200,1.000000,8.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,1.000000

In [16]:
data.isna

<bound method DataFrame.isna of       Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0    7.2500    0      1     0       0       0       0
1               2  38.0   71.2833    1      1     0       0       0       0
2               3  26.0    7.9250    1      0     0       0       0       0
3               4  35.0   53.1000    1      1     0       0       0       0
4               5  35.0    8.0500    0      0     0       0       0       0
...           ...   ...       ...  ...    ...   ...     ...     ...     ...
1304         1305  28.0    8.0500    0      0     0       0       0       0
1305         1306  39.0  108.9000    1      0     0       0       0       0
1306         1307  38.5    7.2500    0      0     0       0       0       0
1307         1308  28.0    8.0500    0      0     0       0       0       0
1308         1309  28.0   22.3583    0      1     0       0       0       0

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0          0  ...        0        0        0       3        0        0
1          0  ...        0        0        0       1        0        0
2          0  ...        0        0        0       3        0        0
3          0  ...        0        0        0       1        0        0
4          0  ...        0        0        0       3        0        0
...      ...  ...      ...      ...      ...     ...      ...      ...
1304       0  ...        0        0        0       3        0        0
1305       0  ...        0        0        0       1        0        0
1306       0  ...        0        0        0       3        0        0
1307       0  ...        0        0        0       3        0        0
1308       0  ...        0        0        0       3        0        0

      Embarked  zero.17  zero.18  2urvived
0          2.0        0        0         0
1          0.0        0        0         1
2          2.0        0        0         1
3          2.0        0        0         1
4          2.0        0        0         0
...        ...      ...      ...       ...
1304       2.0        0        0         0
1305       0.0        0        0         0
1306       2.0        0        0         0
1307       2.0        0        0         0
1308       0.0        0        0         0

[1309 rows x 28 columns]>

In [17]:
data.isna().any()

Passengerid    False
Age            False
Fare           False
Sex            False
sibsp          False
zero           False
zero.1         False
zero.2         False
zero.3         False
zero.4         False
zero.5         False
zero.6         False
Parch          False
zero.7         False
zero.8         False
zero.9         False
zero.10        False
zero.11        False
zero.12        False
zero.13        False
zero.14        False
Pclass         False
zero.15        False
zero.16        False
Embarked        True
zero.17        False
zero.18        False
2urvived       False
dtype: bool

In [18]:
data.isna().sum()

Passengerid    0
Age            0
Fare           0
Sex            0
sibsp          0
zero           0
zero.1         0
zero.2         0
zero.3         0
zero.4         0
zero.5         0
zero.6         0
Parch          0
zero.7         0
zero.8         0
zero.9         0
zero.10        0
zero.11        0
zero.12        0
zero.13        0
zero.14        0
Pclass         0
zero.15        0
zero.16        0
Embarked       2
zero.17        0
zero.18        0
2urvived       0
dtype: int64

# MISSING VALUE TREATMENT

# 2nd method

In [19]:
df2=data["Age"].fillna(29.699118)

In [20]:
#check missing value by columnswith count
df2.isna().sum()

0

# 1st method

In [21]:
df2=data.fillna(data.mean())

In [23]:
#check missing value bycolumnswith count
df2.isna().sum()

Passengerid    0
Age            0
Fare           0
Sex            0
sibsp          0
zero           0
zero.1         0
zero.2         0
zero.3         0
zero.4         0
zero.5         0
zero.6         0
Parch          0
zero.7         0
zero.8         0
zero.9         0
zero.10        0
zero.11        0
zero.12        0
zero.13        0
zero.14        0
Pclass         0
zero.15        0
zero.16        0
Embarked       0
zero.17        0
zero.18        0
2urvived       0
dtype: int64